name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/OpenListTeam/cf-worker-api.git
          git fetch upstream

      - name: Merge Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge upstream/main --no-edit --strategy-option theirs
          git push origin main
